from __future__ import annotations

from theoria.cli.constants import (
    AUTHOR_TRUNCATE_MEDIUM,
    AUTHOR_TRUNCATE_SHORT,
    CITATION_TITLE_TRUNCATE,
    DEFAULT_ENTRIES_DISPLAY_LIMIT,
    DEFAULT_HISTORY_LIMIT,
    MAX_ERRORS_DISPLAY,
    MAX_ISSUES_DISPLAY,
    MAX_UNUSED_LABELS_DISPLAY,
    MAX_WARNINGS_DISPLAY,
    OAUTH_CALLBACK_TIMEOUT,
    OBJECTIONS_THRESHOLD,
    TITLE_TRUNCATE_LENGTH,
)
from theoria.cli.display import GOODBYE_MSG, INTERRUPTED_MSG, truncate

__all__ = [
    "AUTHOR_TRUNCATE_MEDIUM",
    "AUTHOR_TRUNCATE_SHORT",
    "CITATION_TITLE_TRUNCATE",
    "DEFAULT_ENTRIES_DISPLAY_LIMIT",
    "DEFAULT_HISTORY_LIMIT",
    "GOODBYE_MSG",
    "INTERRUPTED_MSG",
    "MAX_ERRORS_DISPLAY",
    "MAX_ISSUES_DISPLAY",
    "MAX_UNUSED_LABELS_DISPLAY",
    "MAX_WARNINGS_DISPLAY",
    "OAUTH_CALLBACK_TIMEOUT",
    "OBJECTIONS_THRESHOLD",
    "TITLE_TRUNCATE_LENGTH",
    "truncate",
]
