from __future__ import annotations

OBJECTIONS_THRESHOLD = 3

DEFAULT_HISTORY_LIMIT = 20
DEFAULT_ENTRIES_DISPLAY_LIMIT = 20

TITLE_TRUNCATE_LENGTH = 40
AUTHOR_TRUNCATE_SHORT = 25
AUTHOR_TRUNCATE_MEDIUM = 30
CITATION_TITLE_TRUNCATE = 35
SESSION_TITLE_TRUNCATE = 50

OAUTH_CALLBACK_TIMEOUT = 300

MAX_ISSUES_DISPLAY = 3
MAX_ERRORS_DISPLAY = 10
MAX_WARNINGS_DISPLAY = 5
MAX_UNUSED_LABELS_DISPLAY = 10
